// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"database/sql"
	"later/pkg/parse"
	"later/pkg/repository"
	"later/pkg/server"
	"later/pkg/service"
)

// Injectors from wire.go:

func InitializeContent(db *sql.DB) server.Content {
	domainRepository := repository.NewDomainRepository(db)
	domainManager := service.NewDomainManager(domainRepository)
	content := parse.NewContent(domainManager)
	contentRepository := repository.NewContentRepository(db)
	contentManager := service.NewContentManager(contentRepository)
	serverContent := server.NewContent(content, contentManager)
	return serverContent
}

func InitializeDomain(db *sql.DB) server.DomainServer {
	domainRepository := repository.NewDomainRepository(db)
	domainManager := service.NewDomainManager(domainRepository)
	domainServer := server.NewDomainServer(domainManager)
	return domainServer
}

func InitializeFriend(db *sql.DB) server.FriendServer {
	user := repository.NewUser(db)
	userManager := service.NewUserManager(user)
	friend := repository.NewFriend(db)
	friendManager := service.NewFriendManager(userManager, friend)
	friendServer := server.NewFriendServer(friendManager)
	return friendServer
}

func InitializeFriendRequest(db *sql.DB) server.FriendRequestServer {
	friendRequestRepository := repository.NewFriendRequestRepository(db)
	friendRequestManager := service.NewFriendRequestManager(friendRequestRepository)
	friendRequestServer := server.NewFriendRequestServer(friendRequestManager)
	return friendRequestServer
}

func InitializeShare(db *sql.DB) server.ShareServer {
	share := repository.NewShare(db)
	userContent := repository.NewUserContent(db)
	userContentManager := service.NewUserContentManager(userContent)
	shareManager := service.NewShareManager(share, userContentManager)
	contentRepository := repository.NewContentRepository(db)
	contentManager := service.NewContentManager(contentRepository)
	user := repository.NewUser(db)
	userManager := service.NewUserManager(user)
	domainRepository := repository.NewDomainRepository(db)
	domainManager := service.NewDomainManager(domainRepository)
	content := parse.NewContent(domainManager)
	shareServer := server.NewShareServer(shareManager, contentManager, userManager, content)
	return shareServer
}

func InitializeUserContent(db *sql.DB) server.UserContentServer {
	userContent := repository.NewUserContent(db)
	userContentManager := service.NewUserContentManager(userContent)
	userContentServer := server.NewUserContentServer(userContentManager)
	return userContentServer
}

func InitializeUser(db *sql.DB) server.UserServer {
	user := repository.NewUser(db)
	userManager := service.NewUserManager(user)
	userServer := server.NewUserServer(userManager)
	return userServer
}
