// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"database/sql"
	"later/pkg/parse"
	"later/pkg/repository"
	"later/pkg/server"
	"later/pkg/service"
)

// Injectors from wire.go:

func InitializeContent(db *sql.DB) server.Content {
	domainRepository := repository.NewDomainRepository(db)
	domainManager := service.NewDomainManager(domainRepository)
	content := parse.NewContent(domainManager)
	contentRepository := repository.NewContentRepository(db)
	contentManager := service.NewContentManager(contentRepository)
	serverContent := server.NewContent(content, contentManager)
	return serverContent
}
