POST http://localhost:8080/auth/login
Client-Id: bc42c734-992a-463a-9602-36218ce03152
Authorization: Basic glump:pass



# POST https://later-api.appspot.com/auth/login
# Client-Id: bc42c734-992a-463a-9602-36218ce03152
# Authorization: Basic lucashmoney:343!Mcrdd