POST http://localhost:8000/chats/for-user
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODc5NDA1NDQsImlhdCI6MTU4NzkzOTY0NCwidXNlclNlc3Npb25faWQiOiIxYjBjNGI3NS1jZTI0LTQ1NWItYjNkYi05OTJiZTNkZmU2MDEifQ.7fJSDRP_ReLxAHgp-HTtpqNQo01k_VfjBETDJQ0hQ60