# POST http://localhost:8000/content/create

# {
#     "url": "https://soundcloud.com/itskforest/stwo-kmh-lovin-u"
# }

GET http://localhost:8000/user-content/filter?saved=true&user_id=2ef129c3-1301-4959-9710-df31688e88d4&search=Trum

# GET http://localhost:8000/content/preview
#     ?url=/content/preview?url=https://www.nytimes.com/2020/04/13/world/coronavirus-news-world-international-global.html?referringSource=articleShare

# PUT http://localhost:8000/user-content/save

# {
#     "id": "3f3f9f14-6634-4a4f-b460-1aa938932acd",
#     "tag": "footy"
# }

# PUT http://localhost:8000/user-content/delete

# {
#     "id": "2c77324a-411f-432e-b62e-e7398735363d"
# }