# POST http://localhost:8000/content/create

# {
#     "url": "https://soundcloud.com/itskforest/stwo-kmh-lovin-u"
# }

# GET http://localhost:8000/user-content/filter
#     ?user_id=b6e05c09-0f62-4757-95f5-ea855adc4915

# PUT http://localhost:8000/user-content/archive

# {
#     "id": "1ef551dc-0faa-4c5c-bce8-a9cf80540de0",
#     "tag": "mixes"
# }

# PUT http://localhost:8000/user-content/delete

# {
#     "id": "2c77324a-411f-432e-b62e-e7398735363d"
# }