# POST http://localhost:8000/content/create

# {
#     "url": "https://soundcloud.com/itskforest/stwo-kmh-lovin-u"
# }

GET http://192.168.254.64:8000/user-content/filter
    ?user_id=b6e05c09-0f62-4757-95f5-ea855adc4915
    &archived=true

# PUT http://localhost:8000/user-content/archive

# {
#     "id": "3f3f9f14-6634-4a4f-b460-1aa938932acd",
#     "tag": "footy"
# }

# PUT http://localhost:8000/user-content/delete

# {
#     "id": "2c77324a-411f-432e-b62e-e7398735363d"
# }