POST http://localhost:8000/shares/new

{
    "sender_user_id": "4774ec20-fc35-4190-8f95-d22e5c092f8f",
    "recipient_user_ids": ["d29e3ba3-d083-4238-96d7-63c20369f3da"],
    "url": "https://www.latimes.com/california/story/2020-04-18/california-north-states-cannabis-industry-jackpot"
}