POST http://localhost:8000/shares/new

{
    "sender_user_id": "efa605a8-efb4-4a85-8548-55f5eafa5a21",
    "recipient_user_ids": ["fdeff714-8f43-4083-ac3f-229cd1783c0c"],
    "url": "https://www.wellplated.com/baked-salmon-in-foil/"
}