GET http://localhost:8000/users/search

# GET http://localhost:8000/users/by-id?user_id=23be1933-f90c-42e4-b8b1-b7ec733d9e4d

# POST http://localhost:8000/users/sign-up

# {
#     "username": "glump",
#     "first_name": "Glumpo",
#     "last_name": "McSqueefy",
#     "email": "glump@gmail.com",
#     "phone_number": "9999999999"
# }